# Site settings
title: 徐国忠Blog
author: 徐国忠
email: 991875160@qq.com
description: New Tech, New Thought.
cover: assets/images/radhakrishna.jpg

# 服务选项
baseurl: /blog
logo: assets/images/logo.png

kramdown:
  input: GFM

