# Site settings
title: GeekLab
author: 徐国忠
email: 991875160@qq.com
description: New Tech, New Thought.
cover: /assets/images/radhakrishna.jpg

# 服务选项
baseurl: ""
logo: /assets/images/logo.jpg

paginate: 10

kramdown:
  input: GFM

plugins:
  - jekyll-paginate